name: Build and Push Frontend Image

on:
  push:
    branches:
      - master
    paths:
      - 'IzvorniKod/frontend/**'      # Trigger only on changes in the /frontend directory
  workflow_dispatch:

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    env:
      FRONTEND_DEPLOY_HOOK: ${{ secrets.FRONTEND_DEPLOY_HOOK }}

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3

      - name: Set Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: IzvorniKod/frontend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('IzvorniKod/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install
        working-directory: IzvorniKod/frontend

      - name: Install Vite manually
        run: npm install vite --save-dev
        working-directory: IzvorniKod/frontend

      - name: Install React plugin for Vite
        run: npm install @vitejs/plugin-react --save-dev
        working-directory: IzvorniKod/frontend

      - name: Set executable permissions for Vite
        run: chmod +x node_modules/.bin/vite
        working-directory: IzvorniKod/frontend

      - name: Build frontend
        run: npm run build
        working-directory: IzvorniKod/frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./IzvorniKod/frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest

      - name: Trigger release
        if: ${{ env.FRONTEND_DEPLOY_HOOK }}
        run: curl ${{ env.FRONTEND_DEPLOY_HOOK }}